/**
 * Builds a real `.docx` (OOXML) for the approval note, dependency-free (see
 * `zip.js`'s header for why). Hand-written XML for exactly the parts Word and
 * LibreOffice both need to open the file clean — no named styles (a `w:pStyle`
 * reference with no matching `styles.xml` entry is a common cause of "found
 * unreadable content, do you want to recover" prompts), only direct run/
 * paragraph formatting.
 *
 * FR12: titleblock, reference number, cited clauses traceable to their
 * provenance (page + region — CONTEXT.md "Provenance crop"), a signature
 * block, and a provenance footer carrying a content hash.
 */

import { createZip } from "./zip.js";

/** Escape the five XML-significant characters; every piece of model- or user-supplied text passes through this before it reaches a run. */
function escapeXml(value) {
	return String(value)
		.replaceAll("&", "&amp;")
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll('"', "&quot;")
		.replaceAll("'", "&apos;");
}

/** One `w:p` with a single run, half-point size, optional bold/italic. */
function paragraph(text, { bold = false, italic = false, sizeHalfPoints = 22, alignment } = {}) {
	const rpr = `<w:rPr>${bold ? "<w:b/>" : ""}${italic ? "<w:i/>" : ""}<w:sz w:val="${sizeHalfPoints}"/></w:rPr>`;
	const ppr = alignment === undefined ? "" : `<w:pPr><w:jc w:val="${alignment}"/></w:pPr>`;
	return `<w:p>${ppr}<w:r>${rpr}<w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r></w:p>`;
}

/** Provenance line for one cited clause: page and the exact bounding box it was read from. */
function clauseSourceLine(clause) {
	const region = clause.region;
	return `page ${clause.page}, region left ${region.left} top ${region.top} width ${region.width} height ${region.height}` + (clause.tag === undefined ? "" : ` (${clause.tag})`);
}

/**
 * @param {object} note
 * @param {string} note.title - titleblock heading.
 * @param {string} note.referenceNumber
 * @param {string} note.generatedAt - ISO 8601 timestamp for the titleblock.
 * @param {string} note.sourceReport - the ingested document the clauses were read from.
 * @param {Array<{ text: string, page: number, region: { left: number, top: number, width: number, height: number }, tag?: string }>} note.clauses
 * @param {string} note.contentHash - hex-encoded digest, printed in the footer.
 * @returns the complete `.docx` file as a Buffer.
 */
export function buildApprovalNoteDocx(note) {
	const bodyParagraphs = [
		paragraph(note.title, { bold: true, sizeHalfPoints: 32 }),
		paragraph(`Reference: ${note.referenceNumber}`, { bold: true, sizeHalfPoints: 22 }),
		paragraph(`Generated: ${note.generatedAt}`, { sizeHalfPoints: 20 }),
		paragraph(`Source report: ${note.sourceReport}`, { sizeHalfPoints: 20 }),
		paragraph("Cited findings", { bold: true, sizeHalfPoints: 26 }),
		...note.clauses.flatMap((clause, index) => [
			paragraph(`${index + 1}. ${clause.text}`, { sizeHalfPoints: 22 }),
			paragraph(`Source: ${clauseSourceLine(clause)}`, { italic: true, sizeHalfPoints: 18 }),
		]),
		paragraph("Signatures", { bold: true, sizeHalfPoints: 26 }),
		paragraph("Prepared by: _________________________        Date: _______________", { sizeHalfPoints: 22 }),
		paragraph("Approved by: _________________________        Date: _______________", { sizeHalfPoints: 22 }),
	].join("");

	const documentXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' +
		`<w:body>${bodyParagraphs}` +
		"<w:sectPr>" +
		'<w:footerReference w:type="default" r:id="rIdFooter1"/>' +
		'<w:pgSz w:w="12240" w:h="15840"/>' +
		'<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>' +
		"</w:sectPr>" +
		"</w:body>" +
		"</w:document>";

	const footerXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' +
		paragraph(`Provenance — SHA-256 content hash: ${note.contentHash}. Generated by Blind Flange, not pre-authored.`, {
			italic: true,
			sizeHalfPoints: 16,
			alignment: "center",
		}) +
		"</w:ftr>";

	const contentTypesXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
		'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
		'<Default Extension="xml" ContentType="application/xml"/>' +
		'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' +
		'<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>' +
		'<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>' +
		'<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>' +
		"</Types>";

	const rootRelsXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
		'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' +
		'<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>' +
		'<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>' +
		"</Relationships>";

	const documentRelsXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
		'<Relationship Id="rIdFooter1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>' +
		"</Relationships>";

	const coreXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">' +
		`<dc:title>${escapeXml(note.title)}</dc:title>` +
		"<dc:creator>Blind Flange</dc:creator>" +
		`<dcterms:created xsi:type="dcterms:W3CDTF">${escapeXml(note.generatedAt)}</dcterms:created>` +
		"</cp:coreProperties>";

	const appXml =
		'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
		'<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">' +
		"<Application>Blind Flange</Application>" +
		"</Properties>";

	return createZip([
		{ name: "[Content_Types].xml", data: Buffer.from(contentTypesXml, "utf8") },
		{ name: "_rels/.rels", data: Buffer.from(rootRelsXml, "utf8") },
		{ name: "docProps/core.xml", data: Buffer.from(coreXml, "utf8") },
		{ name: "docProps/app.xml", data: Buffer.from(appXml, "utf8") },
		{ name: "word/document.xml", data: Buffer.from(documentXml, "utf8") },
		{ name: "word/_rels/document.xml.rels", data: Buffer.from(documentRelsXml, "utf8") },
		{ name: "word/footer1.xml", data: Buffer.from(footerXml, "utf8") },
	]);
}
