/**
 * The approval-note tool (Story 5.4).
 *
 * FR12: a completed set of findings comes out as a real `.docx` — titleblock,
 * reference number, cited clauses traceable to their provenance, a signature
 * block, and a provenance footer carrying a content hash — generated by a
 * real tool dispatched through the ordinary registry, never pre-authored.
 *
 * `ui-deliverables` recognises a produced file by render intent, not tool
 * name: a `generic` card whose `kind` is `edit`, reading `locations[].path`
 * (`packages/client/ui-deliverables`'s own `turn-deliverables.ts`, verified
 * from source). `presentCall` below returns exactly that shape, echoing the
 * model-facing path the same way `str_replace_editor`'s own `insert` case
 * does — unresolved, so the produced-files row and the "Open"/"Show in
 * folder" actions ride the harness's own existing path-opening wiring rather
 * than a second one this package would have to maintain.
 *
 * Written structurally against the harness's `ToolDefinition` shape, like
 * `../findings/tool.js`, rather than through
 * `defineTool` — this package resolves nothing from the harness's own
 * installed packages (`../model-plane/llm-adapter.js` explains why: a
 * `link:`-mounted plugin resolves a bare import from its own real on-disk
 * path, where none of the harness's packages live).
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, isAbsolute, resolve as resolvePath } from "node:path";
import { loadFleet } from "../registry/loader.js";
import { lastRoutingDecision, runtimeModelForCurrentTurn } from "../router/dispatch.js";
import { imagesThisTurn, toolsRunThisTurn } from "../trace/turn.js";
import { buildAuditTrail } from "./audit-trail.js";
import { buildApprovalNoteDocx } from "./docx.js";

export const APPROVAL_NOTE_TOOL_NAME = "bf_approval_note";

/** Keep a reference number usable as a filename: letters, digits, dash and underscore only. */
function sanitizeForFilename(value) {
	return String(value).replaceAll(/[^A-Za-z0-9_-]+/g, "-");
}

/**
 * Where the note is written, workspace-relative — a pure function of the
 * tool's own arguments so `presentCall` (which never sees the session cwd)
 * and `execute` (which resolves this against it) always agree, without the
 * model having to pick a path itself.
 * @param args - the tool's arguments, or a partial/malformed shape `presentCall` must still survive.
 */
function outputRelativePath(args) {
	const reference = typeof args?.referenceNumber === "string" && args.referenceNumber !== "" ? args.referenceNumber : "untitled";
	return `deliverables/approval-note-${sanitizeForFilename(reference)}.docx`;
}

/** Throws with a message naming exactly what is wrong, mirroring `tool-pwsh`'s own `validatePwshArgs`. */
function validateArgs(args) {
	if (typeof args?.title !== "string" || args.title.trim() === "") {
		throw new Error("invalid title: expected a non-empty string");
	}
	if (typeof args?.referenceNumber !== "string" || args.referenceNumber.trim() === "") {
		throw new Error("invalid referenceNumber: expected a non-empty string");
	}
	if (typeof args?.sourceReport !== "string" || args.sourceReport.trim() === "") {
		throw new Error("invalid sourceReport: expected a non-empty string");
	}
	if (!Array.isArray(args?.clauses) || args.clauses.length === 0) {
		throw new Error("invalid clauses: expected a non-empty array");
	}
	for (const [index, clause] of args.clauses.entries()) {
		if (typeof clause?.text !== "string" || clause.text.trim() === "") {
			throw new Error(`invalid clauses[${index}].text: expected a non-empty string`);
		}
	}
}

/** The exact content the hash covers: everything that makes this note *this* note, independent of how it is rendered. */
function contentHashOf(args) {
	const canonical = JSON.stringify({
		title: args.title,
		referenceNumber: args.referenceNumber,
		sourceReport: args.sourceReport,
		clauses: args.clauses,
	});
	return createHash("sha256").update(canonical).digest("hex");
}

/**
 * Build the approval-note tool definition.
 * @param {() => Date} [now] - override for tests; defaults to the real clock.
 * @returns a harness `ToolDefinition`.
 */
/**
 * @param {(() => Date) | { now?: () => Date, providerName?: string }} [options]
 *   A function keeps the original single-argument call working; an object also
 *   carries the active provider name, which the note discloses — a reply served
 *   from a stored response must say so inside the file, not only on screen
 *   (ADR-0001).
 */
export function createApprovalNoteTool(options = {}) {
	const now = typeof options === "function" ? options : (options.now ?? (() => new Date()));
	const providerName = typeof options === "function" ? "unknown" : (options.providerName ?? "unknown");
	return {
		name: APPROVAL_NOTE_TOOL_NAME,
		description:
			"Generate a signed approval note as a real .docx from a set of cited clauses. " +
			"Quote each clause from the source it came from rather than paraphrasing it. " +
			"The produced file appears in the deliverables row with Open and Show-in-folder actions.",
		parameters: {
			type: "object",
			properties: {
				title: { type: "string", description: "Titleblock heading, e.g. \"Approval Note\"." },
				referenceNumber: { type: "string", description: "A reference number for this note, e.g. \"NRC-APPR-0001\"." },
				sourceReport: { type: "string", description: "The document or image the clauses were read from." },
				clauses: {
					type: "array",
					minItems: 1,
					description: "Findings to cite.",
					items: {
						type: "object",
						properties: {
							text: { type: "string", description: "The finding, in full." },
							tag: { type: "string", description: "Equipment tag this finding concerns, if any." },
						},
						required: ["text"],
						additionalProperties: false,
					},
				},
			},
			required: ["title", "referenceNumber", "sourceReport", "clauses"],
			additionalProperties: false,
		},
		output: {
			schema: {
				type: "object",
				additionalProperties: false,
				properties: {
					path: { type: "string" },
					referenceNumber: { type: "string" },
					contentHash: { type: "string" },
					clauseCount: { type: "number" },
				},
				required: ["path", "referenceNumber", "contentHash", "clauseCount"],
			},
			render: (_args, value) => [
				{
					type: "text",
					text: `Approval note ${value.referenceNumber} written to ${value.path} (${value.clauseCount} cited findings, SHA-256 ${value.contentHash}).`,
				},
			],
		},
		/** Real file I/O against the real disk, dispatched every call — nothing pre-authored. */
		async execute(args, exec) {
			validateArgs(args);
			const contentHash = contentHashOf(args);
			const relativePath = outputRelativePath(args);
			const cwd = exec?.agent?.session?.header?.cwd;
			const absolutePath = isAbsolute(relativePath) ? relativePath : resolvePath(cwd ?? process.cwd(), relativePath);
			mkdirSync(dirname(absolutePath), { recursive: true });

			// The audit trail is assembled from the same state the live panels read —
			// the router's own decision and the dispatch resolved from it — rather than
			// from a parallel record kept for the document's benefit. A second source of
			// truth for "which model answered" is a second thing to be wrong, and the
			// copy inside the file is the one nobody can check against the screen once
			// the file has been emailed.
			//
			// Never allowed to fail the deliverable: a note without its reasoning is
			// worth less than one with it, and worth far more than an error.
			let auditTrail;
			try {
				auditTrail = buildAuditTrail({
					routing: lastRoutingDecision(),
					dispatch: runtimeModelForCurrentTurn(loadFleet().loaded),
					providerName,
					images: imagesThisTurn(),
					// This tool's own call is included, because "generated the note" is a
					// step in the work and a list that omits its own last action reads as
					// incomplete to anyone checking it.
					tools: [...toolsRunThisTurn(), { name: APPROVAL_NOTE_TOOL_NAME, outcome: `${args.clauses.length} clauses cited` }],
				}).lines;
			} catch (error) {
				console.warn(
					`@blind-flange/dsh-client-ui-base: the approval note's audit trail could not be assembled — ${error instanceof Error ? error.message : String(error)}`,
				);
				auditTrail = undefined;
			}

			const buffer = buildApprovalNoteDocx({
				title: args.title,
				referenceNumber: args.referenceNumber,
				generatedAt: now().toISOString(),
				sourceReport: args.sourceReport,
				clauses: args.clauses,
				contentHash,
				auditTrail,
			});
			writeFileSync(absolutePath, buffer);
			return { path: absolutePath, referenceNumber: args.referenceNumber, contentHash, clauseCount: args.clauses.length };
		},
		/** The produced-files row reads exactly this shape — see this file's own header comment. */
		presentCall(args) {
			return {
				card: "generic",
				title: `Generate approval note${typeof args?.referenceNumber === "string" && args.referenceNumber !== "" ? ` ${args.referenceNumber}` : ""}`,
				kind: "edit",
				locations: [{ path: outputRelativePath(args) }],
			};
		},
	};
}
