"""Generate the synthetic scanned inspection report the ingestion stories run against.

Everything in the document is invented. Northcape Refining Company does not exist,
neither does Ravensfell Refinery, and the equipment tags and personnel are made up.
The page says so on itself, in the banner and in the footer, so the sample cannot be
mistaken for a real record belonging to MRPL or to anyone else.

The clean page is composed with ReportLab, rasterised with pypdfium2, then put
through ``scan_artefacts`` so it carries skew, speckle, uneven contrast and softened
edges. A clean render makes OCR look easier than it is, and Story 4.2 has to measure
Tesseract against something honest.

Run it with::

    python services/ingestion/fixtures/generate_sample_report.py

Output is deterministic for a given seed, so re-running it reproduces the committed
files byte for byte.
"""

from __future__ import annotations

import argparse
import math
import pathlib
import tempfile

import numpy as np
import pypdfium2 as pdfium
from reportlab.lib.colors import Color
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

import scan_artefacts

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 46.0

BODY = "Helvetica"
BODY_BOLD = "Helvetica-Bold"
HAND = "Times-Italic"

INK_PRINT = Color(0.08, 0.08, 0.09)
INK_FAINT = Color(0.38, 0.38, 0.40)
INK_PEN = Color(0.10, 0.16, 0.48)
RULE = Color(0.45, 0.45, 0.47)
HEADER_FILL = Color(0.88, 0.88, 0.89)

BANNER = (
    "SYNTHETIC SAMPLE — FICTIONAL COMPANY, PLANT, TAGS AND PERSONNEL — "
    "NOT A REAL INSPECTION RECORD"
)
FOOTER = (
    "Synthetic sample data. Northcape Refining Company and Ravensfell Refinery do not "
    "exist. Generated by services/ingestion/fixtures/generate_sample_report.py"
)


# --------------------------------------------------------------------------- text


def wrap(text: str, font: str, size: float, width: float, drawing: canvas.Canvas) -> list[str]:
    """Greedy word wrap against the real glyph widths of the chosen font."""
    lines: list[str] = []
    line = ""
    for word in text.split():
        candidate = f"{line} {word}".strip()
        if drawing.stringWidth(candidate, font, size) <= width or not line:
            line = candidate
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def paragraph(
    drawing: canvas.Canvas, x: float, y: float, text: str, width: float, size: float = 9.0
) -> float:
    drawing.setFont(BODY, size)
    drawing.setFillColor(INK_PRINT)
    leading = size * 1.42
    for line in wrap(text, BODY, size, width, drawing):
        drawing.drawString(x, y, line)
        y -= leading
    return y


def heading(drawing: canvas.Canvas, x: float, y: float, text: str) -> float:
    drawing.setFont(BODY_BOLD, 9.8)
    drawing.setFillColor(INK_PRINT)
    drawing.drawString(x, y, text)
    return y - 15.0


# -------------------------------------------------------------------------- table


def table(
    drawing: canvas.Canvas,
    x: float,
    y: float,
    widths: list[float],
    rows: list[list[str]],
    size: float = 7.9,
) -> tuple[float, list[tuple[float, float]]]:
    """Draw a ruled table with a bold header row.

    The first row is the header. Cells wrap, and the row grows to fit the tallest
    cell in it. Returns the new baseline and the top and bottom of every row, so a
    pen mark can be anchored to a cell that actually exists rather than to a
    guessed coordinate.
    """
    leading = size * 1.32
    pad_x, pad_y = 4.0, 4.5
    drawing.setLineWidth(0.5)
    bounds: list[tuple[float, float]] = []

    for index, row in enumerate(rows):
        header = index == 0
        font = BODY_BOLD if header else BODY
        wrapped = [
            wrap(str(cell), font, size, width - 2 * pad_x, drawing)
            for cell, width in zip(row, widths)
        ]
        height = max(len(cell) for cell in wrapped) * leading + 2 * pad_y

        if header:
            drawing.setFillColor(HEADER_FILL)
            drawing.rect(x, y - height, sum(widths), height, stroke=0, fill=1)

        drawing.setStrokeColor(RULE)
        drawing.rect(x, y - height, sum(widths), height, stroke=1, fill=0)
        edge = x
        for width in widths[:-1]:
            edge += width
            drawing.line(edge, y - height, edge, y)

        drawing.setFillColor(INK_PRINT)
        drawing.setFont(font, size)
        cell_x = x
        for lines, width in zip(wrapped, widths):
            text_y = y - pad_y - size
            for line in lines:
                drawing.drawString(cell_x + pad_x, text_y, line)
                text_y -= leading
            cell_x += width
        bounds.append((y, y - height))
        y -= height

    return y, bounds


# ---------------------------------------------------------------------- pen marks


def hand_text(
    drawing: canvas.Canvas,
    x: float,
    y: float,
    text: str,
    rng: np.random.Generator,
    size: float = 11.0,
) -> float:
    """Write a line the way a pen does — off the baseline, off the vertical.

    Each glyph is placed on its own rotation and baseline offset. It is a
    simulation of handwriting, not a scan of any, and the fixture README says so.
    """
    drawing.setFillColor(INK_PEN)
    cursor = x
    for character in text:
        if character == " ":
            cursor += size * 0.27
            continue
        glyph_size = size * float(rng.uniform(0.90, 1.10))
        drawing.saveState()
        drawing.translate(cursor, y + float(rng.uniform(-1.1, 1.1)))
        drawing.rotate(float(rng.uniform(-8.0, 8.0)))
        drawing.setFont(HAND, glyph_size)
        drawing.setFillColor(INK_PEN)
        drawing.drawString(0, 0, character)
        drawing.restoreState()
        cursor += drawing.stringWidth(character, HAND, glyph_size) * 0.93 + float(
            rng.uniform(-0.4, 0.7)
        )
    return cursor


def pen_stroke(
    drawing: canvas.Canvas,
    points: list[tuple[float, float]],
    rng: np.random.Generator,
    width: float = 1.15,
) -> None:
    """Join points with a wobbly bezier path, as a pen laid down in one motion."""
    drawing.saveState()
    drawing.setStrokeColor(INK_PEN)
    drawing.setLineWidth(width)
    path = drawing.beginPath()
    path.moveTo(*points[0])
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        # Wobble in proportion to the segment, so a long lead line bows gently and a
        # short one around a loop does not turn into a scallop.
        span = max(6.0, math.hypot(x1 - x0, y1 - y0)) * 0.10
        jitter = lambda: float(rng.uniform(-span, span))  # noqa: E731 - local shorthand
        path.curveTo(
            x0 + (x1 - x0) / 3 + jitter(),
            y0 + (y1 - y0) / 3 + jitter(),
            x0 + 2 * (x1 - x0) / 3 + jitter(),
            y0 + 2 * (y1 - y0) / 3 + jitter(),
            x1,
            y1,
        )
    drawing.drawPath(path, stroke=1, fill=0)
    drawing.restoreState()


def pen_ring(
    drawing: canvas.Canvas,
    centre_x: float,
    centre_y: float,
    radius_x: float,
    radius_y: float,
    rng: np.random.Generator,
) -> None:
    """Ring something on the page, overshooting the way a real circling does."""
    steps = 11
    points = []
    for step in range(steps + 3):
        angle = 2 * np.pi * step / steps
        points.append(
            (
                centre_x + radius_x * float(np.cos(angle)) + float(rng.uniform(-0.7, 0.7)),
                centre_y + radius_y * float(np.sin(angle)) + float(rng.uniform(-0.7, 0.7)),
            )
        )
    pen_stroke(drawing, points, rng, width=1.05)


def pen_signature(
    drawing: canvas.Canvas, x: float, y: float, width: float, rng: np.random.Generator
) -> None:
    """A signature drawn as one continuous cursive stroke.

    Two sine components give the rise and fall of the loops; a third, applied to
    the horizontal, makes the pen briefly travel backwards, which is what makes a
    signature cross itself instead of reading as a row of tent poles.
    """
    samples = 90
    rise_phase, loop_phase, back_phase = rng.uniform(0, 2 * np.pi, size=3)
    rise_rate = float(rng.uniform(2.0, 3.0))
    loop_rate = float(rng.uniform(4.5, 6.5))

    drawing.saveState()
    drawing.setStrokeColor(INK_PEN)
    drawing.setLineWidth(1.35)
    path = drawing.beginPath()
    for index in range(samples):
        t = index / (samples - 1)
        travel = width * (t + 0.05 * float(np.sin(2 * np.pi * 3 * t + back_phase)))
        height = (
            13.0 * float(np.sin(2 * np.pi * rise_rate * t + rise_phase))
            + 6.0 * float(np.sin(2 * np.pi * loop_rate * t + loop_phase))
            + 9.0 * t
        )
        point = (x + travel, y + height + float(rng.uniform(-0.5, 0.5)))
        if index == 0:
            path.moveTo(*point)
        else:
            path.lineTo(*point)
    drawing.drawPath(path, stroke=1, fill=0)
    drawing.restoreState()


# --------------------------------------------------------------------- page frame


def frame(drawing: canvas.Canvas, page_number: int, page_count: int) -> None:
    drawing.setFont(BODY_BOLD, 7.4)
    drawing.setFillColor(INK_FAINT)
    drawing.drawCentredString(PAGE_WIDTH / 2, PAGE_HEIGHT - 26, BANNER)
    drawing.setStrokeColor(RULE)
    drawing.setLineWidth(0.6)
    drawing.line(MARGIN, PAGE_HEIGHT - 33, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 33)

    drawing.setFont(BODY, 6.6)
    drawing.setFillColor(INK_FAINT)
    drawing.drawString(MARGIN, 28, FOOTER)
    drawing.drawRightString(PAGE_WIDTH - MARGIN, 28, f"Page {page_number} of {page_count}")
    drawing.line(MARGIN, 38, PAGE_WIDTH - MARGIN, 38)


def letterhead(drawing: canvas.Canvas, y: float) -> float:
    drawing.setFont(BODY_BOLD, 15.0)
    drawing.setFillColor(INK_PRINT)
    drawing.drawString(MARGIN, y, "NORTHCAPE REFINING COMPANY (FICTIONAL)")
    y -= 14
    drawing.setFont(BODY, 8.6)
    drawing.setFillColor(INK_FAINT)
    drawing.drawString(MARGIN, y, "Ravensfell Refinery · Unit 22, Crude Distillation · Mechanical Integrity Department")
    y -= 16
    drawing.setStrokeColor(INK_PRINT)
    drawing.setLineWidth(1.1)
    drawing.line(MARGIN, y, PAGE_WIDTH - MARGIN, y)
    return y - 22


def meta_block(drawing: canvas.Canvas, y: float, entries: list[tuple[str, str]]) -> float:
    """Two columns of label/value pairs, the way a report titleblock reads."""
    column_width = (PAGE_WIDTH - 2 * MARGIN) / 2
    start_y = y
    for index, (label, value) in enumerate(entries):
        column = index % 2
        row = index // 2
        x = MARGIN + column * column_width
        line_y = start_y - row * 13.5
        drawing.setFont(BODY_BOLD, 8.0)
        drawing.setFillColor(INK_FAINT)
        drawing.drawString(x, line_y, label)
        drawing.setFont(BODY, 8.6)
        drawing.setFillColor(INK_PRINT)
        drawing.drawString(x + 82, line_y, value)
    rows = (len(entries) + 1) // 2
    return start_y - rows * 13.5 - 10


# ------------------------------------------------------------------- the document


def compose(path: pathlib.Path, rng: np.random.Generator) -> None:
    drawing = canvas.Canvas(str(path), pagesize=A4)
    drawing.setTitle("Synthetic sample inspection report")
    text_width = PAGE_WIDTH - 2 * MARGIN

    # ---- page one ----------------------------------------------------------
    frame(drawing, 1, 2)
    y = letterhead(drawing, PAGE_HEIGHT - 62)

    drawing.setFont(BODY_BOLD, 12.4)
    drawing.setFillColor(INK_PRINT)
    drawing.drawString(MARGIN, y, "STATIC EQUIPMENT EXTERNAL INSPECTION REPORT")
    y -= 20

    y = meta_block(
        drawing,
        y,
        [
            ("Report no.", "NRC/RVF/INSP/2026-0417"),
            ("Procedure", "NRC-INS-STD-014 Rev 3"),
            ("Inspection date", "12 August 2026"),
            ("Unit", "22 — Crude Distillation"),
            ("Inspector", "R. Kulkarni, Level II (fictional)"),
            ("Reviewed by", "S. Marathe, Inspection Engineer (fictional)"),
            ("Inspection type", "External, in service"),
            ("Next due", "August 2028"),
        ],
    )

    y = heading(drawing, MARGIN, y, "1.  Scope")
    y = paragraph(
        drawing,
        MARGIN,
        y,
        "This report covers the routine external inspection of static equipment and "
        "associated piping in Unit 22 carried out on 12 August 2026 with the unit in "
        "service. Visual examination was supplemented by ultrasonic thickness readings "
        "at the condition monitoring locations listed in section 4. No internal "
        "examination was performed and no equipment was opened. Findings are recorded "
        "against the tag numbers held in the plant register.",
        text_width,
    )
    y -= 12

    y = heading(drawing, MARGIN, y, "2.  Equipment covered")
    y, _ = table(
        drawing,
        MARGIN,
        y,
        [62, 196, 88, 82, 75],
        [
            ["Tag", "Description", "Design press. (barg)", "Design temp. (°C)", "Last external"],
            ["V-2201", "Overhead accumulator, crude column", "9.5", "120", "2024-07"],
            ["E-1104A", "Crude / residue exchanger, channel end", "24.0", "310", "2023-11"],
            ["P-3302B", "Reflux pump, standby", "16.0", "95", "2025-02"],
            ["PSV-2207A", "Relief valve, accumulator outlet", "9.5", "120", "2024-04"],
            ["TK-0450", "Slop tank, fixed roof", "Atmospheric", "60", "2022-09"],
        ],
    )
    y -= 18

    y = heading(drawing, MARGIN, y, "3.  Findings")
    findings_widths = [26, 62, 218, 52, 145]
    y, finding_rows = table(
        drawing,
        MARGIN,
        y,
        findings_widths,
        [
            ["No.", "Tag", "Observation", "Severity", "Recommended action"],
            [
                "1",
                "V-2201",
                "Paint blistering on the south shell over roughly 0.4 m², adjacent to "
                "nozzle N3. No metal loss visible.",
                "Minor",
                "Clean and recoat at the next shutdown.",
            ],
            [
                "2",
                "E-1104A",
                "Insulation cladding open at the channel end. Corrosion under "
                "insulation suspected over a 1.2 m run.",
                "Major",
                "Strip cladding and UT scan before restart.",
            ],
            [
                "3",
                "PSV-2207A",
                "Test tag expired 04-2026. No current bench certificate held against "
                "this tag in the register.",
                "Major",
                "Withdraw and bench test. Fit spare.",
            ],
            [
                "4",
                "P-3302B",
                "Mechanical seal weeping at the outboard face, approximately three "
                "drops per minute.",
                "Minor",
                "Monitor weekly and plan a seal change.",
            ],
            [
                "5",
                "L-2210",
                "Support shoe displaced 18 mm at pipe rack bent 14. Line resting on "
                "the guide edge.",
                "Minor",
                "Reset the shoe and verify hanger load.",
            ],
        ],
    )

    # Ring the severity of finding 2 and write the annotation in the clear space
    # below the table, with a lead line back to what it refers to. Anchoring to the
    # row bounds keeps the pen off the printed text no matter how the cells wrap.
    severity_centre = MARGIN + sum(findings_widths[:3]) + findings_widths[3] / 2
    ring_top, ring_bottom = finding_rows[2]
    pen_ring(
        drawing,
        severity_centre,
        (ring_top + ring_bottom) / 2,
        findings_widths[3] / 2 - 3,
        (ring_top - ring_bottom) / 2 - 2,
        rng,
    )
    annotation_y = y - 34
    hand_text(drawing, MARGIN + 214, annotation_y, "scaffold needed before UT", rng, size=11.0)
    pen_stroke(
        drawing,
        [(MARGIN + 208, annotation_y + 4), (severity_centre - 8, ring_bottom - 4)],
        rng,
    )

    drawing.showPage()

    # ---- page two ----------------------------------------------------------
    frame(drawing, 2, 2)
    y = PAGE_HEIGHT - 62

    drawing.setFont(BODY_BOLD, 9.0)
    drawing.setFillColor(INK_FAINT)
    drawing.drawString(MARGIN, y, "NRC/RVF/INSP/2026-0417 — continued")
    y -= 24

    y = heading(drawing, MARGIN, y, "4.  Thickness readings")
    y = paragraph(
        drawing,
        MARGIN,
        y,
        "Readings taken with a calibrated digital thickness gauge, couplant applied, at "
        "the condition monitoring locations held in the plant register. Values in "
        "millimetres.",
        text_width,
    )
    y -= 10
    y, _ = table(
        drawing,
        MARGIN,
        y,
        [40, 176, 66, 70, 82, 69],
        [
            ["CML", "Location", "Nominal", "Measured", "Min. allowable", "Status"],
            ["01", "V-2201 shell, course 1", "12.00", "11.42", "9.60", "Accept"],
            ["02", "V-2201 shell, course 2", "12.00", "11.08", "9.60", "Accept"],
            ["03", "V-2201 bottom head", "14.00", "12.91", "10.20", "Accept"],
            ["04", "E-1104A channel, 3 o'clock", "16.00", "13.05", "12.70", "Watch"],
            ["05", "E-1104A shell, mid course", "16.00", "15.44", "12.70", "Accept"],
            ["06", "L-2210 elbow, 6 o'clock", "9.27", "7.16", "6.90", "Watch"],
        ],
    )
    y -= 20

    y = heading(drawing, MARGIN, y, "5.  Conclusion")
    y = paragraph(
        drawing,
        MARGIN,
        y,
        "Unit 22 static equipment remains fit for continued service until the next "
        "scheduled shutdown, subject to the two major findings in section 3 being "
        "closed out. CML 04 on E-1104A and CML 06 on L-2210 are within 0.5 mm of their "
        "minimum allowable thickness and are placed on a six-monthly reading interval. "
        "A non-conformance report is to be raised against PSV-2207A, which is operating "
        "outside its certification interval.",
        text_width,
    )
    y -= 26

    hand_text(drawing, MARGIN + 12, y, "Agreed - raise NCR-114 and", rng, size=11.5)
    hand_text(drawing, MARGIN + 12, y - 17, "re-inspect after Nov S/D.", rng, size=11.5)
    y -= 52

    drawing.setStrokeColor(INK_PRINT)
    drawing.setLineWidth(0.6)
    drawing.line(MARGIN, y, MARGIN + 190, y)
    drawing.line(PAGE_WIDTH - MARGIN - 190, y, PAGE_WIDTH - MARGIN, y)
    drawing.setFont(BODY, 8.0)
    drawing.setFillColor(INK_FAINT)
    drawing.drawString(MARGIN, y - 12, "Inspector — R. Kulkarni (fictional)")
    drawing.drawString(PAGE_WIDTH - MARGIN - 190, y - 12, "Reviewed — S. Marathe (fictional)")

    pen_signature(drawing, MARGIN + 14, y + 6, 150, rng)
    pen_signature(drawing, PAGE_WIDTH - MARGIN - 176, y + 5, 142, rng)
    hand_text(drawing, PAGE_WIDTH - MARGIN - 90, y - 30, "14/08/26", rng, size=10.5)

    drawing.showPage()
    drawing.save()


# ------------------------------------------------------------------- rasterising


def rasterise(pdf_path: pathlib.Path, dpi: int) -> list[np.ndarray]:
    """Render every page of the clean PDF to a greyscale array."""
    document = pdfium.PdfDocument(str(pdf_path))
    try:
        pages = []
        for index in range(len(document)):
            bitmap = document[index].render(scale=dpi / 72.0, grayscale=True)
            pages.append(np.asarray(bitmap.to_numpy(), dtype=np.uint8).squeeze())
        return pages
    finally:
        document.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dpi", type=int, default=300, help="raster resolution, default 300")
    parser.add_argument("--seed", type=int, default=26117, help="RNG seed, default 26117")
    parser.add_argument(
        "--out-dir",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent,
        help="where the sample is written, default alongside this script",
    )
    arguments = parser.parse_args()

    rng = np.random.default_rng(arguments.seed)
    arguments.out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as workspace:
        clean = pathlib.Path(workspace) / "clean.pdf"
        compose(clean, rng)
        rendered = rasterise(clean, arguments.dpi)

    # Skew carries a floor as well as a ceiling. A page that happens to draw an
    # angle near zero is a clean render again, and the whole point of the fixture
    # is that it is not one.
    scanned = [
        scan_artefacts.scan(
            page,
            rng,
            degrees=float(rng.choice([-1.0, 1.0]) * rng.uniform(0.35, 0.95)),
            radius=max(1, round(arguments.dpi / 260)),
        )
        for page in rendered
    ]

    for number, page in enumerate(scanned, start=1):
        target = arguments.out_dir / f"sample-inspection-report-p{number}.png"
        scan_artefacts.write_png(target, page, arguments.dpi)
        print(f"wrote {target.name}  {page.shape[1]}x{page.shape[0]} px")

    pdf_target = arguments.out_dir / "sample-inspection-report.pdf"
    scan_artefacts.write_scan_pdf(pdf_target, scanned, arguments.dpi)
    print(f"wrote {pdf_target.name}  {len(scanned)} pages, image only, no text layer")


if __name__ == "__main__":
    main()
