/**
 * Tests for the audit trail that travels inside the deliverable
 * (`deliverables/audit-trail.js`).
 *
 * The live surfaces explain a turn only while you are looking at them. This is
 * the part that survives the file being emailed, so what gets tested is whether
 * it stays honest under the awkward cases: a fact it could not determine, a reply
 * that came from a stored response, OCR that came from a capture rather than a
 * live pass. In each of those a comfortable summary would be easy to write and
 * would be worse than nothing.
 *
 *     node --test plugins/dsh-client-ui-base/test/
 */

import assert from "node:assert/strict";
import test from "node:test";
import { inflateRawSync } from "node:zlib";
import { buildAuditTrail } from "../lib/deliverables/audit-trail.js";
import { buildApprovalNoteDocx } from "../lib/deliverables/docx.js";

const ROUTING = {
	taskType: "document",
	scored: [
		{ name: "Qwen/Qwen3-VL-2B-Instruct", score: 6, matched: [{ capability: "document-understanding", points: 3 }] },
		{ name: "Qwen/Qwen2.5-Coder-1.5B-Instruct", score: 2, matched: [{ capability: "general-reasoning", points: 1 }] },
	],
	excluded: [],
	selected: "Qwen/Qwen3-VL-2B-Instruct",
	tied: false,
	allZero: false,
};

const DISPATCH = { runtimeId: "bf-vision", member: "Qwen/Qwen3-VL-2B-Instruct", reason: "routed" };

const LIVE_INGESTION = { report: "sample-inspection-report.pdf", source: "live", seconds: 7.36, findings: 156 };

test("the trail names the lane, the score that chose the model, and the model that answered", () => {
	const { lines, complete } = buildAuditTrail({
		routing: ROUTING,
		dispatch: DISPATCH,
		providerName: "local",
		ingestion: LIVE_INGESTION,
		tools: [{ name: "bf_report_findings", outcome: "156 lines", seconds: 7.4 }],
	});
	assert.equal(complete, true);
	const text = lines.join("\n");

	assert.match(text, /Task type: document/);
	// The score, not just the winner: a reader has to be able to disagree with the
	// choice, which needs the numbers that made it.
	assert.match(text, /Qwen\/Qwen3-VL-2B-Instruct — score 6 \(document-understanding \+3\)/);
	assert.match(text, /Qwen\/Qwen2\.5-Coder-1\.5B-Instruct — score 2/);
	assert.match(text, /Answered by: Qwen\/Qwen3-VL-2B-Instruct, running locally as "bf-vision"/);
	assert.match(text, /156 OCR lines read from sample-inspection-report\.pdf on this machine in 7\.4s/);
	assert.match(text, /1\. bf_report_findings — 156 lines \(7\.4s\)/);
});

test("an exclusion is printed with its reason, because that is the router declining rather than preferring", () => {
	const { lines } = buildAuditTrail({
		routing: {
			...ROUTING,
			taskType: "drawing",
			excluded: [
				{
					name: "Qwen/Qwen2.5-Coder-1.5B-Instruct",
					reason: { code: "modality-missing", detail: 'task type "drawing" needs a member that accepts image input' },
				},
			],
		},
		dispatch: DISPATCH,
		providerName: "local",
		ingestion: LIVE_INGESTION,
	});
	assert.match(lines.join("\n"), /excluded: task type "drawing" needs a member that accepts image input/);
});

test("a replayed reply says so inside the file, not only on screen", () => {
	// ADR-0001's disclosure has to survive the document being emailed. A note that
	// implies local inference it never did is the failure that ADR exists about.
	const { lines } = buildAuditTrail({ routing: ROUTING, dispatch: DISPATCH, providerName: "replay", ingestion: LIVE_INGESTION });
	assert.match(lines.join("\n"), /served from a stored response, not generated by a model on this machine/);
});

test("a capture read is not described as a live OCR pass", () => {
	const { lines } = buildAuditTrail({
		routing: ROUTING,
		dispatch: DISPATCH,
		providerName: "local",
		ingestion: { report: "sample-inspection-report.pdf", source: "capture", findings: 156, detail: "the service was not running" },
	});
	const text = lines.join("\n");
	assert.match(text, /read from the committed capture of sample-inspection-report\.pdf, not a live OCR pass/);
	assert.match(text, /the service was not running/);
});

test("a fact that could not be determined is printed as unrecorded, never omitted", () => {
	// Omitting it would leave a document that looks complete. Saying "not
	// recorded" lets a reviewer notice, which is the whole point of the block.
	const { lines, complete } = buildAuditTrail({});
	assert.equal(complete, false);
	const text = lines.join("\n");
	assert.match(text, /Task type: not recorded/);
	assert.match(text, /Source text: not recorded/);
	assert.match(text, /Tools run: none recorded/);
	assert.match(text, /printed as unrecorded rather than omitted/);
});

test("a routing decision that never reached a model says which model answered instead, and why", () => {
	const { lines } = buildAuditTrail({
		routing: ROUTING,
		dispatch: { runtimeId: null, member: "Qwen/Qwen3-VL-2B-Instruct", reason: "member-has-no-runtime-id" },
		providerName: "local",
		ingestion: LIVE_INGESTION,
	});
	// A silent fallback to the default model looks exactly like a routing
	// decision, which is why the reason token is printed.
	assert.match(lines.join("\n"), /the local provider's default model — the router's choice was not dispatched \(member-has-no-runtime-id\)/);
});

test("a fallback classification is flagged, so nobody reads it as a decision", () => {
	const { lines } = buildAuditTrail({
		routing: { ...ROUTING, fallback: true },
		dispatch: DISPATCH,
		providerName: "local",
		ingestion: LIVE_INGESTION,
	});
	assert.match(lines.join("\n"), /no classifier rule matched; this is the fallback/);
});

test("egress is absent rather than sourced from somewhere else", () => {
	// FR15 requires the counted zero to be a count of egress/denied events. A
	// counter kept alongside would be a second source of truth for the one number
	// this product's claim rests on. Until the deliverable can read those events,
	// it says nothing about egress — and this asserts that silence, so nobody
	// "helpfully" adds an unsourced number later.
	const { lines } = buildAuditTrail({ routing: ROUTING, dispatch: DISPATCH, providerName: "local", ingestion: LIVE_INGESTION });
	assert.doesNotMatch(lines.join("\n"), /[Oo]utbound network attempts/);

	// It is carried when a caller genuinely has the count.
	const withCount = buildAuditTrail({ routing: ROUTING, dispatch: DISPATCH, ingestion: LIVE_INGESTION, egressDenied: 0 });
	assert.match(withCount.lines.join("\n"), /Outbound network attempts during this session: 0, counted rather than asserted/);
});

/**
 * Unzip to `{ name: text }`, the same way `docx.test.js` does — with an
 * independent reader, so the assertion is about what a `.docx` consumer would
 * see rather than about what our own writer believes it wrote.
 */
function unzipToText(zip) {
	const parts = {};
	let offset = 0;
	while (offset + 30 <= zip.length && zip.readUInt32LE(offset) === 0x04034b50) {
		const compressedSize = zip.readUInt32LE(offset + 18);
		const nameLength = zip.readUInt16LE(offset + 26);
		const extraLength = zip.readUInt16LE(offset + 28);
		const nameStart = offset + 30;
		const name = zip.toString("ascii", nameStart, nameStart + nameLength);
		const dataStart = nameStart + nameLength + extraLength;
		parts[name] = inflateRawSync(zip.subarray(dataStart, dataStart + compressedSize)).toString("utf8");
		offset = dataStart + compressedSize;
	}
	return parts;
}

test("the docx carries the trail, escapes it, and omits the heading entirely when there is none", () => {
	const note = {
		title: "Approval Note",
		referenceNumber: "NRC-APPR-0001",
		generatedAt: "2026-08-30T00:00:00.000Z",
		sourceReport: "sample-inspection-report.pdf",
		clauses: [{ text: "Insulation cladding open", page: 1, region: { left: 1, top: 2, width: 3, height: 4 } }],
		contentHash: "abc123",
	};

	const body = unzipToText(
		buildApprovalNoteDocx({
			...note,
			auditTrail: ["Task type: document", "", 'Answered by: a model called "x" & <y>'],
		}),
	)["word/document.xml"];

	assert.match(body, /How this note was produced/);
	// Model- and router-supplied text reaches a run, so it must be escaped like
	// every other value in this document.
	assert.match(body, /a model called &quot;x&quot; &amp; &lt;y&gt;/);
	assert.ok(!body.includes("<y>"), "a raw angle bracket would corrupt the XML tree");
	// The trail sits after the signature block: it is evidence for a reviewer, not
	// content for a signatory, and must not come between the findings and the line
	// somebody signs.
	assert.ok(body.indexOf("How this note was produced") > body.indexOf("Approved by:"));

	// No trail means no empty heading. A section header with nothing under it
	// reads as a bug in the document rather than an absence of data.
	assert.doesNotMatch(unzipToText(buildApprovalNoteDocx(note))["word/document.xml"], /How this note was produced/);
});
