/**
 * Tests for the approval-note tool (`lib/deliverables/tool.js`), Story 5.4.
 * Exercises real filesystem I/O against a temp directory — no in-memory
 * stub of `writeFileSync`, since "generated by a real tool, not
 * pre-authored" is exactly the property under test.
 *
 *     node --test plugins/dsh-client-ui-base/test/
 */

import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { inflateRawSync } from "node:zlib";
import { APPROVAL_NOTE_TOOL_NAME, createApprovalNoteTool } from "../lib/deliverables/tool.js";

function sampleArgs(overrides = {}) {
	return {
		title: "Approval Note",
		referenceNumber: "NRC-APPR-0001",
		sourceReport: "sample-inspection-report.pdf",
		clauses: [
			{
				text: "E-1104A — corrosion under insulation suspected over a 1.2 m run.",
				page: 1,
				region: { left: 560, top: 2048, width: 814, height: 58 },
				tag: "E-1104A",
			},
		],
		...overrides,
	};
}

/** A fake tool-execution context carrying just the session cwd `execute` reads. */
function execWithCwd(cwd) {
	return { agent: { session: { header: { cwd } } } };
}

/** First text part of a zip whose local-file-header offset scan matches `test/docx.test.js`'s. */
function readZipTextPart(buffer, name) {
	let offset = 0;
	while (offset < buffer.length && buffer.readUInt32LE(offset) === 0x04034b50) {
		const compressedSize = buffer.readUInt32LE(offset + 18);
		const nameLength = buffer.readUInt16LE(offset + 26);
		const extraLength = buffer.readUInt16LE(offset + 28);
		const nameStart = offset + 30;
		const entryName = buffer.toString("ascii", nameStart, nameStart + nameLength);
		const dataStart = nameStart + nameLength + extraLength;
		if (entryName === name) return inflateRawSync(buffer.subarray(dataStart, dataStart + compressedSize)).toString("utf8");
		offset = dataStart + compressedSize;
	}
	return undefined;
}

test("registers under the expected tool name", () => {
	assert.equal(createApprovalNoteTool().name, APPROVAL_NOTE_TOOL_NAME);
});

test("writes a real .docx under the session workspace and reports its path", async (t) => {
	const dir = mkdtempSync(join(tmpdir(), "bf-approval-note-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));

	const tool = createApprovalNoteTool();
	const result = await tool.execute(sampleArgs(), execWithCwd(dir));

	assert.equal(result.path, join(dir, "deliverables", "approval-note-NRC-APPR-0001.docx"));
	const written = readFileSync(result.path);
	assert.equal(written.readUInt32LE(0), 0x04034b50, "not a real zip/docx on disk");
	assert.equal(result.clauseCount, 1);
});

test("the written file's footer carries the same content hash the tool reports", async (t) => {
	const dir = mkdtempSync(join(tmpdir(), "bf-approval-note-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));

	const tool = createApprovalNoteTool();
	const args = sampleArgs();
	const result = await tool.execute(args, execWithCwd(dir));

	const expectedHash = createHash("sha256")
		.update(JSON.stringify({ title: args.title, referenceNumber: args.referenceNumber, sourceReport: args.sourceReport, clauses: args.clauses }))
		.digest("hex");
	assert.equal(result.contentHash, expectedHash);

	const footer = readZipTextPart(readFileSync(result.path), "word/footer1.xml");
	assert.match(footer, new RegExp(expectedHash));
});

test("falls back to process.cwd() when no session cwd is available", async (t) => {
	const originalCwd = process.cwd();
	const dir = mkdtempSync(join(tmpdir(), "bf-approval-note-cwd-"));
	process.chdir(dir);
	t.after(() => {
		process.chdir(originalCwd);
		rmSync(dir, { recursive: true, force: true });
	});

	const tool = createApprovalNoteTool();
	const result = await tool.execute(sampleArgs(), {});
	assert.equal(result.path, join(dir, "deliverables", "approval-note-NRC-APPR-0001.docx"));
});

test("rejects a missing title", async () => {
	const tool = createApprovalNoteTool();
	await assert.rejects(() => tool.execute(sampleArgs({ title: "" }), execWithCwd(tmpdir())), /title/);
});

test("rejects an empty clauses array", async () => {
	const tool = createApprovalNoteTool();
	await assert.rejects(() => tool.execute(sampleArgs({ clauses: [] }), execWithCwd(tmpdir())), /clauses/);
});

test("rejects a clause with no region — provenance is not optional", async () => {
	const tool = createApprovalNoteTool();
	const args = sampleArgs({ clauses: [{ text: "unsourced claim", page: 1 }] });
	await assert.rejects(() => tool.execute(args, execWithCwd(tmpdir())), /region/);
});

test("rejects a clause missing a page number", async () => {
	const tool = createApprovalNoteTool();
	const args = sampleArgs({ clauses: [{ text: "x", region: { left: 0, top: 0, width: 1, height: 1 } }] });
	await assert.rejects(() => tool.execute(args, execWithCwd(tmpdir())), /page/);
});

test("presentCall returns the produced-files render intent ui-deliverables reads", () => {
	const tool = createApprovalNoteTool();
	const view = tool.presentCall(sampleArgs());
	assert.equal(view.card, "generic");
	assert.equal(view.kind, "edit");
	assert.deepEqual(view.locations, [{ path: "deliverables/approval-note-NRC-APPR-0001.docx" }]);
});

test("presentCall never throws, even on malformed args", () => {
	const tool = createApprovalNoteTool();
	assert.doesNotThrow(() => tool.presentCall(undefined));
	assert.doesNotThrow(() => tool.presentCall({}));
});

test("the render text names the path and the content hash", async (t) => {
	const dir = mkdtempSync(join(tmpdir(), "bf-approval-note-render-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));

	const tool = createApprovalNoteTool();
	const value = await tool.execute(sampleArgs(), execWithCwd(dir));
	const [block] = tool.output.render(sampleArgs(), value);
	assert.match(block.text, new RegExp(value.contentHash));
	assert.match(block.text, /approval-note-NRC-APPR-0001\.docx/);
});
